### ISSUE TITLE
updated YAML block in documentation when configuring a dark mode option

### ISSUE THREAD

**Issue by mikeoleary** [f5devcentral/modern_app_jumpstart_workshop#84]
In step 3 of the [documentation](https://f5devcentral.github.io/modern_app_jumpstart_workshop/scenario/ab-testing.html), the step for editing the virtual-server.yaml file says that the routes section of the file "should look like this"

````yaml
     - path: /
       matches:
         - conditions:
           - cookie: "app_version"
             value: "dark"
           action:
             pass: spa-dark
````

I believe it should say that we are updating one part of the routes section, and that the yaml block for the path of / should look like this:

````yaml
    - path: /
      action:
        pass: spa
      matches:
        - conditions:
          - cookie: "app_version"
            value: "dark"
          action:
            pass: spa-dark
````

thanks!
